#!/usr/bin/env python3
"""Generate the dedicated EARN HTML and JavaScript assets from shared sources."""

from __future__ import annotations

import argparse
from pathlib import Path


ROOT = Path(__file__).resolve().parent
SOURCE_HTML = ROOT / "dashboard-core.html"
SOURCE_JS = ROOT / "dashboard-core.js"
OUTPUT_HTML = ROOT / "earn" / "earn-core.html"
OUTPUT_JS = ROOT / "earn" / "earn-core.js"
STATIC_LAYOUT_VERSION = "earn-core-20260722-static-layout-20260713-emode-responsive-sky-rate"


def _slice(source: str, start: str, end: str, *, include_end: bool = False) -> str:
    start_index = source.index(start)
    end_index = source.index(end, start_index)
    if include_end:
        end_index += len(end)
    return source[start_index:end_index]


def render_earn_assets(html_path: Path = SOURCE_HTML, js_path: Path = SOURCE_JS) -> tuple[str, str]:
    html_source = html_path.read_text(encoding="utf-8")
    js_source = js_path.read_text(encoding="utf-8")

    header = _slice(html_source, '<header class="site-header anim">', "</header>", include_end=True)
    earn_view = _slice(html_source, "<!-- EARN VIEW -->", "</div><!-- /view-earn -->", include_end=True)
    earn_view = earn_view.replace('id="view-earn" class="view-section"', 'id="view-earn" class="view-section active"', 1)
    date_overlay = _slice(html_source, "<!-- Snapshot Calendar Picker Modal -->", '<footer class="site-footer', include_end=False).rstrip()
    footer = _slice(html_source, '<footer class="site-footer', "</footer>", include_end=True)

    generated_html = f'''<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Dolomite Earn</title>
    <meta name="description" content="Dolomite Earn balances, yield, historical P&amp;L, and verification status.">
    <link rel="shortcut icon" href="favicon.ico" type="image/png">
    <link rel="preconnect" href="https://fonts.googleapis.com">
    <link href="https://fonts.googleapis.com/css2?family=Inter:wght@300;400;500;600;700;800&amp;family=JetBrains+Mono:wght@400;500&amp;display=swap" rel="stylesheet">
    <link rel="stylesheet" href="dashboard-core.css?v=core-split-20260718-earn-fast-path-{STATIC_LAYOUT_VERSION}">
    <link rel="dns-prefetch" href="//api.dolomite.io">
    <link rel="dns-prefetch" href="//coins.llama.fi">
    <link rel="dns-prefetch" href="//subgraph.api.dolomite.io">
    <script src="dolo-address-labels.js?v=dolo-labels-20260624-bot-mm-audit"></script>
</head>
<body class="earn-draft-route">
    <div class="page-wrapper">
{header}
{earn_view}
        <div id="toggle-tooltip-float"></div>
{date_overlay}
{footer}
    </div>
    <div class="toast" id="copy-toast">Address copied!</div>
    <script src="earn/earn-cache-policy.js?v=earn-cache-policy-20260718"></script>
    <script src="earn/earn-rpc-policy.js?v=earn-rpc-policy-20260718"></script>
    <script src="earn/earn-core.js?v=core-split-20260718-ledger-primary-sla-{STATIC_LAYOUT_VERSION}"></script>
    <script src="earn/earn-static-layout.js?v=earn-static-layout-20260722-export"></script>
    <script>
    (() => {{
        const isLocalhost = window.location.hostname === 'localhost';
        const loopback = isLocalhost || window.location.hostname === '127.0.0.1' || window.location.hostname === '::1';
        if (!loopback) return;
        if (new URLSearchParams(window.location.search).get('layoutEditor') !== '1') return;
        const css = document.createElement('link');
        css.rel = 'stylesheet';
        css.href = 'earn/earn-layout-editor.css?v=20260722-2';
        document.head.append(css);
        const script = document.createElement('script');
        script.src = 'earn/earn-layout-editor.js?v=20260722-1';
        document.body.append(script);
    }})();
    </script>
</body>
</html>
'''

    labels = _slice(js_source, "const DOLO_ADDR_LABELS", "// Badge tooltips", include_end=False).rstrip()
    earn_runtime = _slice(js_source, "// ===== EARN TAB NAMESPACE =====", "// Lazy per-view data loading.", include_end=False).rstrip()
    tooltip_runtime = _slice(js_source, "// ═══ UNIFIED PREMIUM TOOLTIP SYSTEM ═══", "// ===== TREASURY NAMESPACE =====", include_end=False).rstrip()
    prelude = f'''/* Generated by build_earn_bundle.py. Do not edit directly. */
function earn_isDedicatedRoutePage() {{ return true; }}
function aprToApy(apr) {{ return (Math.pow(1 + apr / 100 / 365, 365) - 1) * 100; }}
function vedolo_shortAddr(addr) {{ return addr.slice(0, 6) + '…' + addr.slice(-4); }}
{labels}
'''
    generated_js = prelude + earn_runtime + "\n\n" + tooltip_runtime + "\n"
    return generated_html, generated_js


def main() -> int:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--check", action="store_true", help="Fail when generated assets differ from disk")
    args = parser.parse_args()
    html, javascript = render_earn_assets()
    expected = [(OUTPUT_HTML, html), (OUTPUT_JS, javascript)]
    if args.check:
        stale = [str(path.relative_to(ROOT)) for path, value in expected if not path.is_file() or path.read_text(encoding="utf-8") != value]
        if stale:
            raise SystemExit("Stale generated EARN assets: " + ", ".join(stale))
        print("Generated EARN assets are current.")
        return 0
    for path, value in expected:
        path.parent.mkdir(parents=True, exist_ok=True)
        path.write_text(value, encoding="utf-8")
        print(f"Wrote {path.relative_to(ROOT)} ({len(value):,} bytes)")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
