#!/usr/bin/env python3
"""
Data Validation Guard — runs BEFORE git commit in CI/CD.
If any check fails, exits with code 1 → workflow skips commit → production data stays intact.

Usage:
    python3 validate_data.py                     # validate all files
    python3 validate_data.py dolo_flows.json     # validate specific file(s)
"""

import json
import sys
import os
from datetime import datetime, timezone

# ── Validation Rules ─────────────────────────────────────────────────────────
# Each file has: required top-level keys, optional nested checks, and min-size thresholds.

RULES = {
    "dolo_flows.json": {
        "required_keys": ["timestamp", "dolo_price", "periods"],
        "checks": [
            ("periods must have data",     lambda d: len(d.get("periods", {})) >= 3),
            ("dolo_price must be positive", lambda d: d.get("dolo_price", 0) > 0),
        ],
        "min_bytes": 50_000,
    },
    "dolo_holders.json": {
        "required_keys": ["contract", "timestamp", "stats", "holders"],
        "checks": [
            ("holders list must not be empty", lambda d: len(d.get("holders", [])) >= 10),
        ],
        "min_bytes": 10_000,
    },
    "vedolo_holders.json": {
        "required_keys": ["contract", "timestamp", "stats", "holders"],
        "checks": [
            ("holders must have entries", lambda d: len(d.get("holders", [])) >= 10),
        ],
        "min_bytes": 100_000,
    },
    "odolo_flows.json": {
        "required_keys": ["timestamp", "periods"],
        "checks": [
            ("periods must have data", lambda d: len(d.get("periods", {})) >= 3),
        ],
        "min_bytes": 50_000,
    },
    "vedolo_flows.json": {
        "required_keys": ["timestamp", "total_unlocks", "total_locks"],
        "checks": [],
        "min_bytes": 10_000,
    },
    "liquidation_risk.json": {
        "required_keys": ["generatedAt", "globalStats", "chainStats"],
        "checks": [
            ("chainStats must have entries", lambda d: len(d.get("chainStats", {})) >= 1),
        ],
        "min_bytes": 10_000,
    },
    "exercisers_by_address.json": {
        "required_keys": ["updated", "total_addresses", "exercisers"],
        "checks": [
            ("exercisers must have entries", lambda d: len(d.get("exercisers", [])) >= 5),
        ],
        "min_bytes": 50_000,
    },
    "early_exits.json": {
        "required_keys": ["stats", "recent_exits"],
        "checks": [],
        "min_bytes": 1_000,
    },
    "dolomite_tvl.json": {
        "required_keys": ["totalTvl"],
        "checks": [
            ("totalTvl must be positive", lambda d: d.get("totalTvl", 0) > 0),
        ],
        "min_bytes": 1_000,
    },
    "defillama_data.json": {
        "required_keys": ["tvl", "name"],
        "checks": [],
        "min_bytes": 10_000,
    },
    "vedolo_stats.json": {
        "required_keys": ["stats", "timestamp"],
        "checks": [],
        "min_bytes": 100,
    },
    "vedolo_expiry.json": {
        "required_keys": ["buckets", "total_dolo", "timestamp"],
        "checks": [],
        "min_bytes": 100,
    },
    "dolo_price.json": {
        "required_keys": ["price"],
        "checks": [
            ("price must be positive", lambda d: d.get("price", 0) > 0),
        ],
        "min_bytes": 50,
    },
    "odolo_contract_data.json": {
        "required_keys": ["totalSupply", "decimals"],
        "checks": [],
        "min_bytes": 50,
    },
    "metrics_snapshot.json": {
        "required_keys": ["snapshots"],
        "checks": [],
        "min_bytes": 100,
    },
    "avg_lock_data.json": {
        "required_keys": ["avg_lock_days", "total_exercises"],
        "checks": [],
        "min_bytes": 50,
    },
}

# ── Data files stored in data/ subdirectories ────────────────────────────────
# These use glob-style matching for directories with multiple files
DATA_DIR_RULES = {
    "data/earn-netflow": {
        "min_files": 1,
        "file_ext": ".json",
    },
    "data/earn-snapshots": {
        "min_files": 1,
        "file_ext": ".json",
    },
}


# ── Validation Engine ────────────────────────────────────────────────────────

class ValidationResult:
    def __init__(self):
        self.passed = 0
        self.failed = 0
        self.skipped = 0
        self.errors = []

    def ok(self, msg):
        self.passed += 1
        print(f"  ✅ {msg}")

    def fail(self, msg):
        self.failed += 1
        self.errors.append(msg)
        print(f"  ❌ {msg}")

    def skip(self, msg):
        self.skipped += 1
        print(f"  ⏭️  {msg}")


def validate_file(filepath, rules, result):
    """Validate a single JSON data file against its rules."""
    print(f"\n📄 {filepath}")

    # Check file exists
    if not os.path.exists(filepath):
        result.skip(f"File not found (may not be generated by this workflow)")
        return

    # Check minimum file size
    file_size = os.path.getsize(filepath)
    min_bytes = rules.get("min_bytes", 0)
    if file_size < min_bytes:
        result.fail(f"File too small: {file_size:,} bytes (min: {min_bytes:,})")
        return
    result.ok(f"Size: {file_size:,} bytes (min: {min_bytes:,})")

    # Parse JSON
    try:
        with open(filepath, "r") as f:
            data = json.load(f)
    except json.JSONDecodeError as e:
        result.fail(f"Invalid JSON: {e}")
        return
    result.ok("Valid JSON")

    # Check required keys
    for key in rules.get("required_keys", []):
        if key in data:
            result.ok(f"Key '{key}' present")
        else:
            result.fail(f"Missing required key: '{key}'")

    # Run custom checks
    for desc, check_fn in rules.get("checks", []):
        try:
            if check_fn(data):
                result.ok(desc)
            else:
                result.fail(f"Check failed: {desc}")
        except Exception as e:
            result.fail(f"Check error ({desc}): {e}")


def validate_data_dir(dirpath, rules, result):
    """Validate a data subdirectory (must contain minimum number of files)."""
    print(f"\n📁 {dirpath}/")

    if not os.path.isdir(dirpath):
        result.skip(f"Directory not found")
        return

    ext = rules.get("file_ext", ".json")
    files = [f for f in os.listdir(dirpath) if f.endswith(ext)]
    min_files = rules.get("min_files", 1)

    if len(files) >= min_files:
        result.ok(f"{len(files)} {ext} files (min: {min_files})")
    else:
        result.fail(f"Only {len(files)} {ext} files (min: {min_files})")

    # Validate each JSON file in directory is parseable
    bad = 0
    for fname in files:
        fpath = os.path.join(dirpath, fname)
        try:
            with open(fpath) as f:
                json.load(f)
        except json.JSONDecodeError:
            bad += 1
            result.fail(f"Invalid JSON: {fname}")

    if bad == 0 and files:
        result.ok(f"All {len(files)} files valid JSON")


def main():
    print("=" * 60)
    print("🔍 Dolomite Data Validation Guard")
    print(f"   {datetime.now(timezone.utc).strftime('%Y-%m-%d %H:%M UTC')}")
    print("=" * 60)

    result = ValidationResult()

    # Determine which files to validate
    if len(sys.argv) > 1:
        # Validate specific files passed as arguments
        targets = sys.argv[1:]
        for target in targets:
            basename = os.path.basename(target)
            if basename in RULES:
                validate_file(target, RULES[basename], result)
            else:
                print(f"\n⚠️  No rules defined for: {target}")
                result.skip(f"No validation rules for {target}")
    else:
        # Validate all known files
        for filename, rules in RULES.items():
            validate_file(filename, rules, result)

        for dirpath, rules in DATA_DIR_RULES.items():
            validate_data_dir(dirpath, rules, result)

    # Summary
    print("\n" + "=" * 60)
    print(f"📊 Results: {result.passed} passed, {result.failed} failed, {result.skipped} skipped")

    if result.errors:
        print("\n🚨 FAILURES:")
        for err in result.errors:
            print(f"   • {err}")
        print("\n⛔ Validation FAILED — commit will be skipped to protect production data.")
        sys.exit(1)
    else:
        print("\n✅ All validations passed — safe to commit.")
        sys.exit(0)


if __name__ == "__main__":
    main()
