import json
import unittest
from pathlib import Path


ROOT = Path(__file__).resolve().parents[1]
PORTFOLIO_HTML = ROOT / "portfolio-preview.html"
EXERCISERS_JSON = ROOT / "exercisers_by_address.json"
GENERATE_EXERCISERS = ROOT / "generate_exercisers.py"


class PortfolioPreviewContractsTest(unittest.TestCase):
    @classmethod
    def setUpClass(cls):
        cls.html = PORTFOLIO_HTML.read_text(encoding="utf-8")

    def test_open_borrows_uses_risk_positions_ux(self):
        self.assertIn("liquidation_risk.json", self.html)
        self.assertIn("buildRiskBorrowRows", self.html)
        self.assertIn('class="pf-table pf-borrow-positions"', self.html)
        self.assertIn('data-sort="hf" data-table="bor"', self.html)
        self.assertIn('data-sort="address" data-table="bor">Address', self.html)
        self.assertIn('>Account</th>', self.html)
        self.assertIn("function accountNumberCell(account)", self.html)
        self.assertIn("function shortAccountNumber(account)", self.html)
        self.assertIn("${accountNumberCell(r.account)}", self.html)
        self.assertIn("Dolomite account number", self.html)
        self.assertIn('data-copy="${esc(number)}"', self.html)
        self.assertIn('account: p.accountNumber == null ? "" : String(p.accountNumber)', self.html)
        self.assertNotIn('account: String(p.accountNumber || "")', self.html)
        self.assertIn('data-sort="emode" data-table="bor"', self.html)
        self.assertIn("function emodeCell(active)", self.html)
        self.assertIn("pf-emode-badge", self.html)
        self.assertIn("E-Mode applies special risk parameters", self.html)
        self.assertIn("function portfolioAddressCell(addr)", self.html)
        self.assertIn("holder-wallet", self.html)
        self.assertIn("addr-mono addr-tooltip-wrap", self.html)
        self.assertIn("addr-copy", self.html)
        self.assertIn("View on DeBank", self.html)
        self.assertIn("data-copy", self.html)
        self.assertIn("navigator.clipboard.writeText(value)", self.html)
        self.assertNotIn(">Open borrow</div>", self.html)
        self.assertNotIn("positionLabel(r)", self.html)
        self.assertNotIn("Position #", self.html)
        self.assertIn("'dGM' : DOLO_CDN + 'GMX.", self.html)
        self.assertIn("'dGMX' : DOLO_CDN + 'GMX.", self.html)
        self.assertNotIn(">Position<span", self.html)
        self.assertNotIn('pf-mini-chip">E-mode', self.html)
        self.assertIn("buildFallbackBorrowRows", self.html)
        self.assertIn("riskBorrows.length ? riskBorrows : buildFallbackBorrowRows(chainResults, addr)", self.html)
        self.assertIn(".pf-hf-badge.unknown", self.html)
        self.assertIn("pf-hf-dot", self.html)
        self.assertIn("${hfText(r.hf)}", self.html)
        self.assertIn('td colspan="7"', self.html)
        self.assertIn("collateralTokens", self.html)
        self.assertIn("debtTokens", self.html)
        self.assertIn("BORROW_DUST_USD = 1", self.html)
        self.assertIn('borFilter: { chains: new Set(), q: "", hideDust: true }', self.html)
        self.assertIn("data-borrow-hide-dust", self.html)
        self.assertIn(">Hide Dust<", self.html)
        self.assertIn("TELEGRAM_ICON", self.html)
        self.assertIn("set-alert-header-btn", self.html)
        self.assertIn("Dolomite_SuperGus_bot", self.html)
        self.assertIn(">Set Alert<", self.html)
        self.assertIn("pf-collateral-main", self.html)
        self.assertIn("pf-debt-main", self.html)
        self.assertIn("color:#34d399", self.html)
        self.assertIn("color:#f87171", self.html)
        self.assertIn("No non-dust borrow positions match the filter.", self.html)

    def test_odolo_pending_summary_does_not_count_paired_dolo(self):
        self.assertIn("const total = held + ve + vOTok;", self.html)
        self.assertNotIn("const total = held + ve + vPair;", self.html)
        self.assertIn("DOLO paired · returned on claim", self.html)
        self.assertIn("const exClaimTxs = exTxs.filter(t => t && t.usdc != null);", self.html)
        self.assertIn("const exVe = exClaimTxs.reduce", self.html)
        self.assertNotIn("const exVe = exTxs.reduce", self.html)
        self.assertIn("option cost", self.html)
        self.assertIn("oDOLO converted into veDOLO", self.html)
        self.assertNotIn("DOLO paid ·", self.html)
        self.assertNotIn("DOLO paired · in veDOLO", self.html)

    def test_vedolo_odolo_exercises_exclude_pairing_noise(self):
        self.assertIn('id="pf-exercises-section"', self.html)
        self.assertIn("veDOLO Position Activity", self.html)
        self.assertIn("Current veDOLO", self.html)
        self.assertIn('class="pf-table pf-exercise-table"', self.html)
        self.assertIn("vedolo_flows.json", self.html)
        self.assertIn("buildExerciseRows(cardData.exer, vedoloFlows, addr, cardData.vedolo)", self.html)
        self.assertIn("currentVedolo", self.html)
        self.assertIn("seenTokenIds", self.html)
        self.assertIn("flowLocks = (flows && flows.locks) || []", self.html)
        self.assertIn("lockByTokenId", self.html)
        self.assertIn("function isDoloPairExerciseTx(tx)", self.html)
        self.assertIn('if (paidTokenKey(tx) === "DOLO") return true;', self.html)
        self.assertIn('if (methodId === "0xf3621c90") return true;', self.html)
        self.assertIn("return doloPaid > 0 && tx.usdc == null;", self.html)
        self.assertIn("function isStableExerciseTx(tx)", self.html)
        self.assertIn("function pairedDoloAmount(tx)", self.html)
        self.assertIn(".filter(tx => isStableExerciseTx(tx) || isDoloPairExerciseTx(tx))", self.html)
        self.assertIn('action: isPair ? "Pair oDOLO + DOLO" : "Exercise oDOLO"', self.html)
        self.assertIn('route: isPair ? "pair" : "odolo"', self.html)
        self.assertIn("pairedDolo: doloPaired", self.html)
        self.assertIn("Paired oDOLO with DOLO before veDOLO claim", self.html)
        self.assertIn("if (tokenId && !isPair) seenTokenIds.add(tokenId);", self.html)
        self.assertIn('if (lock.isOdolo) return;', self.html)
        self.assertIn('"Deposit veDOLO"', self.html)
        self.assertIn('"direct"', self.html)
        self.assertIn("DOLO locked directly, no purchase price", self.html)
        self.assertIn('action: isAirdrop ? "Claim Airdrop" : "Deposit veDOLO"', self.html)
        self.assertIn('route: isAirdrop ? "airdrop" : "direct"', self.html)
        self.assertIn("Airdrop allocation locked as 2-year veDOLO", self.html)
        self.assertIn('action: "Transfer veDOLO"', self.html)
        self.assertIn('route: "transfer"', self.html)
        self.assertIn('transferDirection: direction', self.html)
        self.assertIn('isTransfer: true', self.html)
        self.assertIn("flows && flows.transfers", self.html)
        self.assertIn("currentVedolo && currentVedolo.token_details", self.html)
        self.assertIn("fallbackCurrent: true", self.html)
        self.assertIn("Current holder of position #", self.html)
        self.assertIn("position date · tx pending", self.html)
        self.assertIn('id="pf-exercises-filters"', self.html)
        self.assertIn("EXERCISE_ROUTES", self.html)
        self.assertIn("buildExerciseFilters(state.exercises, state.exFilter, renderAll)", self.html)
        self.assertIn("const routeCounts = rows.reduce", self.html)
        self.assertIn('class="dd-opt-count"', self.html)
        self.assertIn('<colgroup><col style="width:148px"><col style="width:160px"><col style="width:116px"><col style="width:118px"><col style="width:118px"><col style="width:96px"><col style="width:88px"></colgroup>', self.html)
        self.assertIn("#pf-exercises-section .flow-route-head{text-align:left}", self.html)
        self.assertIn("#pf-exercises-section .pf-route-cell{text-align:left}", self.html)
        self.assertIn("#pf-exercises-section .pf-route-tag.cyan", self.html)
        self.assertIn("#pf-exercises-section .pf-route-tag.pair", self.html)
        self.assertIn("#pf-exercises-section .pf-route-tag.up", self.html)
        self.assertIn("#pf-exercises-section .pf-route-tag.gold", self.html)
        self.assertIn("#pf-exercises-section .pf-route-tag.airdrop", self.html)
        self.assertIn('data-sort="vedolo" data-table="ex">veDOLO', self.html)
        self.assertIn('data-sort="route" data-table="ex">Route', self.html)
        self.assertNotIn('data-sort="action" data-table="ex">Action', self.html)
        self.assertIn('data-sort="pair" data-table="ex">DOLO Paired', self.html)
        self.assertIn('"date","vedolo","pair","lock"', self.html)
        self.assertIn('data-sort="paid" data-table="ex">USDC Paid', self.html)
        self.assertIn('data-sort="price" data-table="ex">Price', self.html)
        self.assertIn('data-sort="lock" data-table="ex">Lock', self.html)
        self.assertNotIn('data-sort="paid" data-table="ex">Cost', self.html)
        self.assertIn('<td class="num">${pairHtml}</td>\n        <td class="num">${paidHtml}</td>\n        <td class="num">${priceHtml}</td>\n        <td class="num">${lockHtml}</td>', self.html)
        self.assertNotIn('<td class="num">${lockHtml}</td>\n        <td class="num">${paidHtml}</td>', self.html)
        self.assertIn('const paidHtml = r.isStableClaim ? `<span class="pf-ex-val pf-ex-usdc">${fmtUSD(r.paid)}</span>`', self.html)
        self.assertIn('const pairHtml = r.isPair ? `<span class="pf-ex-val pf-ex-pair">${fmtToken(r.pairedDolo)}</span>`', self.html)
        self.assertNotIn('${esc(r.paidToken)}</span>` : "—";', self.html)
        self.assertIn("applyExerciseFilter(state.exercises, state.exFilter)", self.html)
        self.assertIn("exerciseRouteTag(r.route, r)", self.html)
        self.assertIn("flow-source-tag pf-route-tag", self.html)
        self.assertIn("oDOLO Exercise", self.html)
        self.assertIn("Pair oDOLO + DOLO", self.html)
        self.assertIn("DOLO Airdrop Claim", self.html)
        self.assertIn("Direct veDOLO", self.html)
        self.assertIn("veDOLO Transfer", self.html)
        self.assertIn('const label = isTransfer ? `Transfer ${row && row.transferDirection === "out" ? "Out" : "In"}` : meta.label;', self.html)
        self.assertIn("Exercise", self.html)
        self.assertIn("Pair", self.html)
        self.assertIn("Airdrop", self.html)
        self.assertIn("Direct", self.html)
        self.assertIn("Transfer", self.html)
        self.assertIn('let opts = "";', self.html)
        self.assertNotIn('data-route="all"', self.html)
        self.assertNotIn('dd-opt-name">All Routes', self.html)
        self.assertIn("if (filterState.routes.size === 0) filterState.routes = defaultExerciseRoutes();", self.html)
        self.assertIn("pf-ex-val pf-ex-ve", self.html)
        self.assertIn("pf-ex-val pf-ex-usdc", self.html)
        self.assertIn("pf-ex-val pf-ex-price", self.html)
        self.assertIn("pf-ex-lock", self.html)
        self.assertIn("exerciseLockBucket(r.lockDays)", self.html)
        self.assertIn("pf-latest-date", self.html)
        self.assertIn("fmtExerciseDateMeta(r)", self.html)
        self.assertIn("fmtExerciseRelativeTime", self.html)
        self.assertIn("fmtExerciseClockTime", self.html)
        self.assertIn("const exerciseSortTimeMs = row =>", self.html)
        self.assertIn('return num > 0 ? (num > 1e12 ? num : num * 1000) : 0;', self.html)
        self.assertIn("flowByHash", self.html)
        self.assertIn("timestamp: exerciseTimeMs(tx) || exerciseTimeMs(flow)", self.html)
        self.assertIn("timestamp: exerciseTimeMs(lock)", self.html)
        self.assertNotIn("exerciseDateMeta", self.html)
        self.assertIn("pf-ex-green", self.html)
        self.assertIn("txExplorer(r.chain, r.hash)", self.html)
        self.assertIn('id="pf-exercises-summary"', self.html)
        self.assertIn("renderExerciseSummary(rows)", self.html)
        self.assertIn("grid-template-columns:repeat(4,minmax(0,1fr))", self.html)
        self.assertIn("min-height:78px", self.html)
        self.assertIn("font-size:14.5px", self.html)
        self.assertIn("pf-exercise-summary-item.accent", self.html)
        self.assertIn("accent-money", self.html)
        self.assertIn("#pf-exercises-section .pf-exercise-summary-sub .accent-money{color:#9ab7c2", self.html)
        self.assertIn("#pf-exercises-section .pf-exercise-summary-value .accent-price{color:#9ab7c2", self.html)
        self.assertIn("#pf-exercises-section .pf-exercise-route-filter .dd-btn", self.html)
        self.assertIn("#pf-exercises-section .pf-exercise-route-filter .dd-panel", self.html)
        self.assertIn("#pf-exercises-section .pf-exercise-route-filter .dd-opt.active .dd-opt-check", self.html)
        self.assertIn("background:var(--pf-ex-green)", self.html)
        self.assertIn("const claimRows = rows.filter(r => r.isStableClaim);", self.html)
        self.assertIn("state.vedoloCurrent", self.html)
        self.assertIn('const activityLocked = rows.filter(r => r.route !== "transfer" && r.route !== "pair").reduce', self.html)
        self.assertIn("const lockedVe = currentVe || activityLocked;", self.html)
        self.assertIn("currentVe || rows.filter", self.html)
        self.assertIn("Total locked", self.html)
        self.assertIn("oDOLO Exercises", self.html)
        self.assertIn("Avg price", self.html)
        self.assertIn("USDC per veDOLO", self.html)
        self.assertIn('<span class="accent-money">${fmtUSD(claimPaid)} USDC paid</span>', self.html)
        self.assertIn('<span class="accent-price">${fmtExercisePrice(avgClaimPrice)}</span>', self.html)
        self.assertIn("Vote power", self.html)
        self.assertIn("Current voting weight", self.html)
        self.assertIn('totalPaired ? ` · ${fmtToken(totalPaired)} DOLO paired` : ""', self.html)
        self.assertNotIn('exerciseSummaryItem(\n        "Airdrops"', self.html)
        self.assertNotIn('exerciseSummaryItem(\n        "Direct"', self.html)
        self.assertNotIn('exerciseSummaryItem(\n        "Transfers"', self.html)
        self.assertNotIn("direct DOLO lock", self.html)
        self.assertNotIn("Not mixed with paired DOLO", self.html)

    def test_odolo_pair_snapshot_matches_transaction_rows(self):
        data = json.loads(EXERCISERS_JSON.read_text(encoding="utf-8"))
        txs = [
            tx
            for exerciser in data.get("exercisers", [])
            for tx in exerciser.get("txs", [])
        ]
        pair_txs = [tx for tx in txs if str(tx.get("paid_token", "")).upper() == "DOLO"]
        self.assertGreater(len(pair_txs), 0)
        self.assertEqual(len(pair_txs), data.get("total_dolo_pair_exercises"))
        self.assertAlmostEqual(
            sum(float(tx.get("vedolo") or 0) for tx in pair_txs),
            float(data.get("total_dolo_pair_vedolo") or 0),
            places=1,
        )
        self.assertTrue(all(tx.get("dolo_paid") for tx in pair_txs))
        self.assertTrue(all(isinstance(tx.get("timestamp"), int) and tx["timestamp"] > 0 for tx in txs))
        generator = GENERATE_EXERCISERS.read_text(encoding="utf-8")
        self.assertIn('"timestamp": timestamp', generator)

    def test_hash_update_stays_on_portfolio_route_under_base_tag(self):
        self.assertIn('history.replaceState(null, "", `${location.pathname}${location.search}#${addr}`);', self.html)
        self.assertNotIn('history.replaceState(null, "", "#" + addr);', self.html)


if __name__ == "__main__":
    unittest.main()
